#!/bin/sh
#configuration jelly enviroment parameter 
drod=/home/cedar/ws/src/Android/src
drod_framworks=$drod/frameworks/base
oprofile=$drod/external/oprofile
armtools=$drod/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin

#clear old PATH
export PATH=$CEDAR_LOGIN
#used openjdk1.7
#setup enviroment jdk1.6.0_45
#if [ -f /$HOME/.$USER/local/java/bin/jdk1.6.0_45 ] ; then
#    source /$HOME/.$USER/local/java/bin/jdk1.6.0_45
#fi
if [ -d "$drod" ] ; then
    cd "$drod"
    source build/envsetup.sh
else
    echo "Can not find dirtory $drod"
fi

# add now enviroment oprofile and so on
export  PATH=$oprofile:$PATH
export  PATH=$armtools:$PATH
# change dirtory to frameworks
if [ $# -eq 1 ];then
    if [ $1 == frameworks ]; then
        cd $drod
        source build/envsetup.sh
        cd $drod_framworks
    else
        echo "dirtory is not frameworks please check type error"
    fi
fi
ls
