#! /bin/bash
#clear login enviroment PATH
OLD_PATH=$PATH
export PATH=$CEDAR_LOGIN
#configuration enviroment path for crash
drod_ics=/home/cedar/workspace/src/ICS/src
drod_froyo=/home/cedar/workspace/src/Froyo/src
crash_dir=/home/cedar/.cedar/local/crash

tools=/prebuilt/linux-x86/toolchain/arm-eabi-4.2.1/bin/
board=""
version=""
lcd=""
#add colors print for linux shell
. $HOME/.$USER/bin/utils/io/colors/Print

function Usage(){
    printRed "please check you parameter.";
    printRed "-1 BSP12 or -2 BSP13.";
    printRed "-3 V3 or -4 V4.";
    printRed "-h hvga or -w wvga.";
}

function EditerCrash(){
    vim $crash_dir/crash.txt
    exit;
}

function FroyoCrash(){
    cd $drod_froyo
    source build/envsetup.sh;
}

function ICSCrash(){
    cd $drod_ics
    source build/envsetup_infomax.sh
}

#change directory to crash directory
if [ -d "$crash_dir" ] ; then
    cd $crash_dir
else
    printRed "Can not find directory $crash_dir"
fi

while getopts "12t34hw" option
do
    case $option in
        1)
            printGreen "crash analysis Froyo";
            FroyoCrash;
            ;;
        2)
            printGreen "crash analysis ICS";
            ICSCrash;
            ;;
        3)
            printGreen "v3 ";
            version="iM98xx_evb_v3";
            ;;
        4)
            printGreen "v4 ";
            version="iM98xx_evb_v4";
            ;;
        t)
            EditerCrash;
            ;;
        h)
            printGreen "hvga";
            lcd="";
            ;;
        w)
            printGreen "wvga";
            lcd="_wvga";
            ;;
        *)
            Usage;
            ;;
    esac
done




board=$version$lcd
export PATH=$drod_froyo$tools:$PATH
stack --symbols-dir=out/target/product/$board/symbols/ $crash_dir/crash.txt
#restore OLD_PATH
export PATH=$OLD_PATH
