#!/bin/bash
src=/home/cedar/workspace/src
infomax_images=/src/infomax_images
boot=boot.img_iM98xx_evb_
system=system.img_iM98xx_evb_
barebox=barebox.bin_im98xx
recovery=recovery.img_iM98xx_evb_
ps=ecos_ps4010_release.bin
ramloader='ldr_app_rev56(01.01.09).bin'
barebox_v3=_A9-624MHz-AHB-div2_XM-198MHz_A7-143MHz
barebox_v4=_A9-806MHz-AHB-div3_XM-198MHz_A7-130MHz
barebox_vn="";
evb="";
wvga=_;

. $HOME/.$USER/bin/utils/io/colors/Print


#select partation for BSP12 or BSP13
if [ $1 = "-1" ] || [ $1 = "-2" ] ;then
    if [ $1 = "-2" ] ;then
        image=$src/"ICS"/$infomax_images
        cd $image
    else
        image=$src/"Froyo"/$infomax_images
        cd $image
    fi
else
    printRed "partation error please check."
    exit;
fi

if [ $# -eq 2 ] ;then
    if [ $2 = "-e" ] ;then
        printRed "Erase user data.";
        usb-img-dl $1 -e u;
    else if [ $2 = "-A" ] ;then
            printGreen "Erase all image";
            usb-img-dl $1 -A;
            usb-img-dl $1 -b Rm $ramloader $ps
            exit;
        else
            printRed "Please check parameter input.";
            printRed ">>BSP12 -1 or BSP13 -2";
            printRed ">>'-e' for erase user data.";
    fi
    fi
    exit;
fi
if [ $# -ne 4 ] ;then
    printRed "Please check parameter input.";
    printRed "BSP12 -1 or BSP13 -2.";
    printRed "evbv3 -3 or evbv4 -4.";
    printRed "wvga -w or hvga -h.";
    printRed "boot -b system -s all -a.";
    exit;
fi
#select evb version
if [ $2 = "-3" ] || [ $2 = "-4" ] ;then
    if [ $2 = "-3" ] ;then
        printGreen "Burn v3 image at once."
        evb='v3'
        barebox_vn=$barebox_v3
    else
        printGreen "Burn v4 image at once."
        evb='v4'
        barebox_vn=$barebox_v4
    fi
else
    printRed "evb version error please check."
    exit;
fi

#select image wvga or hvga.
if [ $3 = "-w" ] || [ $3 = "-h" ] ;then
    if [ $3 = "-w" ] ;then
        printGreen "Burn wvga image."
        wvga=$wvga'wvga'
    else
        printGreen "Burn hvga image."
        wvga=""
    fi
else
    printGreen "select image error please check."
fi

case $4 in
    "-b")
        barebox=$barebox$evb$wvga$barebox_vn
        printGreen "Burn boot:"$barebox
        usb-img-dl $1 -b b $barebox
        ;;
    "-B")
        boot=$boot$evb$wvga
        printGreen "Burn boot:"$boot
        usb-img-dl $1 -b B $boot
        ;;
    "-s")
        system=$system$evb$wvga
        printGreen "Burn system:"$system
        usb-img-dl $1 -b s $system
        ;;
    "-a")
        printGreen "Burn all at once."
        barebox=$barebox$evb$wvga$barebox_vn
        boot=$boot$evb$wvga
        system=$system$evb$wvga
        recovery=$recovery$evb$wvga
        usb-img-dl $1 -A
        usb-img-dl $1 -b RbBrsm $ramloader $barebox $boot $recovery $system $ps
        ;;
esac
