#!/bin/bash
src=/home/cedar/workspace/src
infomax_images=/src/infomax_images
boot=boot.img_iM98xx_evb_
system=system.img_iM98xx_evb_
barebox=barebox.bin_im98xx
recovery=recovery.img_iM98xx_evb_
ps=ecos_ps4010_release.bin
ramloader='ldr_app_rev56(01.01.09).bin'
barebox_v3=_A9-624MHz-AHB-div2_XM-198MHz_A7-143MHz
barebox_v4=_A9-806MHz-AHB-div3_XM-198MHz_A7-130MHz
barebox_vn="";
evb="";
wvga=_;

. $HOME/.$USER/bin/utils/io/colors/Print

function Usage(){
    printRed "Please check parameter input.";
    printRed "BSP12 -1 or BSP13 -2.";
    printRed "evbv3 -3 or evbv4 -4.";
    printRed "wvga -w or hvga -h.";
    printRed "boot -b system -s all -a.";
    exit;
}

#select partation for BSP12.
function BSP12Partation(){
    image=$src/"Froyo"/$infomax_images
    cd $image
}
function BSP13Partation(){
    image=$src/"ICS"/$infomax_images
    cd $image
}

#select evb version
function evb3(){
    evb='v3'
    barebox_vn=$barebox_v3
}
function evb4(){
    evb='v4'
    barebox_vn=$barebox_v4
}

#screen size
function hvga(){
    wvga=""
}
function wvga(){
    wvga=$wvga'wvga'
}


function BurnBarebox(){
    barebox=$barebox$evb$wvga$barebox_vn
    printGreen "Burn barebox:"$barebox
    usb-img-dl $1 -b b $barebox
}
function BurnBoot(){
    boot=$boot$evb$wvga
    printGreen "Burn boot:"$boot
    usb-img-dl $1 -b B $boot
}
function BurnSystem(){
    system=$system$evb$wvga
    printGreen "Burn system:"$system
    usb-img-dl $1 -b s $system
}

function BurnAll(){
    barebox=$barebox$evb$wvga$barebox_vn
    boot=$boot$evb$wvga
    system=$system$evb$wvga
    recovery=$recovery$evb$wvga
    printGreen "Ramloader:"$ramloader
    printGreen "Barebox:"$barebox
    printGreen "Boot:"$boot
    printGreen "Recovery:"$recovery
    printGreen "System:"$system
    printGreen "Ps:"$ps
    usb-img-dl $1 -A
    usb-img-dl $1 -b RbBrsm $ramloader $barebox $boot $recovery $system $ps
}

function EraseUserData(){
    usb-img-dl $1 -e u;
    exit;
}

function EraseAll(){
    usb-img-dl $1 -A;
    usb-img-dl $1 Rm $ramloader $ps;
    exit;
}

case $# in
    '2')
        printRed "Eraseing";
        while getopts "eA" option
        do
            case $option in
                e)
                    EraseUserData $1;
                    ;;
                A)
                    EraseAll $1;
                    ;;
                *)
                    Usage;
                    ;;
            esac
        done
        ;;
    '4')
        printGreen "Startup burn image";
        while getopts "1234hwbBsa" option
        do
            case $option in
            1)
                BSP12Partation;
                ;;
            2)
                BSP13Partation;
                ;;
            3)
                evb3;
                ;;
            4)
                evb4;
                ;;
            h)
                hvga;
                ;;
            w)
                wvga;
                ;;

            b)
                BurnBarebox $1;
                ;;
            B)
                BurnBoot $1;
                ;;
            s)
                BurnSystem $1;
                ;;
            a)
                BurnAll $1;
                ;;
            *)
                Usage;
                ;;
            esac
        done
        ;;
    *)
        Usage;
        ;;
esac
