#!/bin/sh
#configuration absolate path for Froyo enviroment parameter
drod=$HOME/ws/src/Froyo/src
oprofile=$drod/external/oprofile
armtools=$drod/prebuilt/linux-x86/toolchain/arm-eabi-4.2.1/bin

#clear old PATH
export PATH=${CEDAR_LOGIN:-`$PATH`}
#setup enviroment jdk 1.5
if [ -f $HOME/.$USER/local/java/bin/jdk1.5 ] ; then
    source $HOME/.$USER/local/java/bin/jdk1.5
fi
if [ -d "$drod" ] ; then
    cd "$drod"
    if [ -f build/envsetup.sh ] ; then
        source build/envsetup.sh
    else
        echo "Can't find file build/envsetup.sh"
        for file in `ls build/envsetup*`;do
            source $file;
        done
    fi
else
    echo "Can not find directory $drod"
fi

# add new enviroment parameter
export  PATH=$oprofile:$PATH
export  PATH=$armtools:$PATH
