#!/bin/bash
#configuration ics enviroment parameter 
drod=$HOME/ws/src/i381/src

#clear old PATH
export PATH=${CEDAR_LOGIN:-`$PATH`}
#setup enviroment jdk1.6
if [ -f $HOME/.$USER/local/java/bin/jdk1.6 ] ; then
    source $HOME/.$USER/local/java/bin/jdk1.6
fi
if [ -d "$drod" ] ; then
    cd "$drod"
    if [ -f build/envsetup_im381.sh ] ; then
        source build/envsetup_im381.sh
    else
        echo "Cann't find file build/envsetup_infomax.sh"
        for file in `ls build/envsetup*` ; do
            source $file;
        done
    fi
else
    echo "Can not find dirtory $drod"
fi