#!/bin/bash
#configuration ics enviroment parameter 
drod=/home/cedar/ws/src/ICS/src
drod_framworks=$drod/frameworks/base
oprofile=$drod/external/oprofile
armtools=$drod/prebuilt/linux-x86/toolchain/arm-eabi-4.2.1/bin

#clear old PATH
export PATH=${CEDAR_LOGIN:-`$PATH`}
#setup enviroment jdk1.6
if [ -f $HOME/.$USER/local/java/bin/jdk1.6 ] ; then
    source $HOME/.$USER/local/java/bin/jdk1.6
fi
if [ -d "$drod" ] ; then
    cd "$drod"
    if [ -f build/envsetup_infomax.sh ] ; then
        source build/envsetup_infomax.sh
    else
        echo "Cann't find file build/envsetup_infomax.sh"
        for file in `ls build/envsetup*` ; do
            source $file;
        done
    fi
else
    echo "Can not find dirtory $drod"
fi

# add now enviroment oprofile and so on
export  PATH=$oprofile:$PATH
export  PATH=$armtools:$PATH
# change dirtory to frameworks
if [ $# -eq 1 ];then
    if [ $1 == frameworks ]; then
        cd $drod
        source build/envsetup_infomax.sh
        cd $drod_framworks
    else
        echo "dirtory is not frameworks please check type error"
    fi
fi
