#!/bin/sh
#configuration jelly enviroment parameter
drod=$HOME/ws/src/XiaoMi/src
drod_framworks=$drod/frameworks/base

#clear old PATH
export PATH=$CEDAR_LOGIN
#setup enviroment jdk1.6
if [ -f /$HOME/.$USER/local/java/bin/jdk1.6 ] ; then
    source /$HOME/.$USER/local/java/bin/jdk1.6
fi
if [ -d "$drod" ] ; then
    cd "$drod"
    source build/envsetup.sh
else
    echo "Can not find dirtory $drod"
fi
