#!/bin/bash
#setup enviroment jdk1.7
if [ -f $HOME/.$USER/local/java/bin/jdk1.7 ] ; then
    source $HOME/.$USER/local/java/bin/jdk1.7
fi

if [ -f $HOME/.$USER/local/adt/android-studio/bin/studio.sh ] ; then
    $HOME/.$USER/local/adt/android-studio/bin/studio.sh
fi
