#!/bin/bash
#configuration ics enviroment parameter 
root_dir=/home/cedar/ws/src/zephyr/src

#clear old PATH
export PATH=${CEDAR_LOGIN:-`$PATH`}
if [ -d "$root_dir" ] ; then
    cd "$root_dir"
    if [ -f zephyr-env.sh ] ; then
        source zephyr-env.sh
    else
        echo "Cann't find file build/envsetup_infomax.sh"
        for file in `ls build/envsetup*` ; do
            source $file;
        done
    fi
else
    echo "Can not find dirtory $drod"
fi

export ZEPHYR_GCC_VARIANT=zephyr
export ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
